# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df639ac5227fcc3e40b0f9e87192293a97bc52b813128c51d5bb74dcf214d10c2a17e60d7abe4080d4b28abac736ac744015b900fb1cae31fb53c21239d6c3bc

test:
  secret_key_base: bebe7882b60b4f9e96633d6a9b574ddd31b94e9f420c01cd4bc3c863e5e63615432c67fb9bed1627e39a0e694844131941e526dbcb8368701c4542e7b48a1030

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
